
server:
  port: 8686
  compression:
    enabled: true
  connection-timeout: 3000

debug: false

#logging:
#  file: /var/log/admin-manager.log

management:
  context-path: /management
  security:
    enabled: false

spring:
  application:
    name: bumishi-blog
  datasource:
    url: jdbc:mysql://localhost:3306/bumishi_blog?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
          max-active: 30
          initial-size: 5
          min-idle: 3
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
  cache:
    guava:
      #spec: maximumSize=500,expireAfterAccess=3600s
      spec: maximumSize=500

 #spring-boot-admin config
  boot:
      admin:
        #这里是admin-manage的地址，/admin是admin-manage中配置的spring.spring.boot.admin.context-path
        url: http://localhost:10000/admin
        context-path: /admin

  thymeleaf:
      cache: false

      prefix: classpath:/public/themes/jiestyle/

blog:
  manage:
    ##允许访问博客管理api的机器
    allow: localhost,127.0.0.1,bumishi.tech
